# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
# 3. For themekit be sure that config dir is prefixed to settings_data.json
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---   

# Dawn CLI3 theme: theme watch -e 
dawn-cli3:
  password: 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
  theme_id: 131786277058
  store: velstar-steven-v2.myshopify.com
  ignore_files:
    - config/settings_data.json # Uncomment this line to avoid resetting theme settings
    - locales/*.json
    - templates/*.json